Support npm specifiers
slack-samples/deno-triage-rotation pull request #33
Opened 2023-10-26 21:18 UTC by WilliamBergamin

### Type of change (place an x in the [ ] that applies)

- [ ] New sample
- [ ] New feature
- [x] Bug fix
- [ ] Documentation

### Summary

This PR aims to update the version of the `deno-slack-hooks` package and enable the project to use `npm` specifiers to import packages

This also resolves #32 

### Requirements

- [x] I’ve checked my submission against the Samples Checklist to ensure it complies with all standards
- [x] I have ensured the changes I am contributing align with existing patterns and have tested and linted my code
- [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct)

2023-10-26 21:19 UTC, filmaj commented
Should this be created as a `pre-release` branch for the upcoming release? Since it includes a freshly-cut SDK version bump, and the automated tests will rely on the existence of a `pre-release` branch?

2023-10-26 21:25 UTC, WilliamBergamin commented
I think this PR or the `pre-release` PR will update the package correctly, just note that the npm specifiers will need to be updated in the samples

2023-10-30 14:19 UTC, filmaj requested changes
Should probably use a versioned `types` package and also move it into a `deps.ts` if it exists?

This PR will also conflict with #34 FYI.

2023-10-30 14:19 UTC, filmaj commented on functions/open_form/blocks.ts
> +} from "npm:@slack/types";
I'd version this, the current version is 2.9.0. I am planning on releasing a 3.0 version soon-ish which will include breaking changes.

2024-04-07 22:56 UTC, Nidacoke approved these changes

2024-04-08 17:48 UTC, filmaj approved these changes
LGTM but def should be tested with an actual `slack deploy` / at least a deno-hooks `build` hook invocation to see if esbuild can handle it or not.

Would be nice to add that to samples' CI, too: can the project be built using the deno `build` hook?

2024-04-08 17:56 UTC, WilliamBergamin commented
🟢 tested with `slack deploy` everything works as expected
🟢 tested with `deno run ... https://deno.land/x/deno_slack_hooks@1.3.0/build.ts` everything builds as expected

2024-04-08 18:00 UTC, merged